version: '3.6'
services:
  mongo:
    container_name: parapaints-mongo
    image: mongo:4.4
    entrypoint:
      - bash
      - -c
      - |
        cp /config/mongo-keyfile /config/keyfile
        chmod 400 /config/keyfile
        chown mongodb -R /config/keyfile
        exec docker-entrypoint.sh $$@
    command: mongod --replSet rs --bind_ip_all --keyFile config/keyfile --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - parapaints
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./apps/api/src/config/mongo-keyfile:/config/mongo-keyfile
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb-cfg
        target: /data/configdb
  # mongo-replicator creates a replica set for transactions support
  mongo-replicator:
    container_name: parapaints-mongo-replicator
    image: mongo:4.4
    entrypoint:
      - bash
      - -c
      - |
        chmod +x /setup.sh
        bash /setup.sh
    volumes:
      - ./bin/setup.sh:/setup.sh
    environment:
      - HOST=mongo
      - PORT=27017
      - USERNAME=root
      - PASSWORD=root
      - REPLICA_SET_NAME=rs
    networks:
      - parapaints
    depends_on:
      - mongo
  redis:
    container_name: parapaints-redis
    image: redis:5.0.5
    command: redis-server --appendonly yes
    hostname: redis
    networks:
      - parapaints
    ports:
      - 6379:6379
  api:
    container_name: parapaints-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development-docker
    networks:
      - parapaints
    volumes:
      - ./apps/api/src:/app/apps/api/src
    ports:
      - 3001:3001
    depends_on:
      - redis
      - mongo-replicator
  migrator:
    container_name: parapaints-migrator
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.migrator
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development-docker
    networks:
      - parapaints
    volumes:
      - ./apps/api/src:/app/apps/api/src
    depends_on:
      - mongo-replicator
  scheduler:
    container_name: parapaints-scheduler
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.scheduler
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - parapaints
    volumes:
      - ./apps/api/src:/app/apps/api/src
    depends_on:
      - mongo-replicator
  web:
    container_name: parapaints-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/public:/app/apps/web/public
    networks:
      - parapaints
    ports:
      - 3002:3002

networks:
  parapaints:
    name: parapaints-network

volumes:
  mongodb:
  mongodb-cfg:
